-- FILE: init_spatial.sql
-- Run this in your Oracle Database (e.g., via SQL Plus or SQL Developer)

-- 1. Cleanup (Optional, removes existing table)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE INCIDENTS_SPATIAL';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

-- 2. Create Table
-- Storing MONGO_ID as VARCHAR2 to link with MongoDB document
CREATE TABLE INCIDENTS_SPATIAL (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    MONGO_ID VARCHAR2(50) NOT NULL UNIQUE, 
    LOCATION SDO_GEOMETRY,
    title VARCHAR2(100), -- specific to this task, store a bit of metadata for quick popup without join
    PRIMARY KEY (ID)
);

-- 3. Update Geometry Metadata
-- Assuming WGS 84 (SRID 4326)
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'INCIDENTS_SPATIAL';

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
) VALUES (
    'INCIDENTS_SPATIAL', 
    'LOCATION', 
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude', -90, 90, 0.005)
    ), 
    4326
);

COMMIT;

-- 4. Create Spatial Index
CREATE INDEX INDX_INCIDENTS_LOC ON INCIDENTS_SPATIAL(LOCATION) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 5. Test Insert (Dummy Data)
INSERT INTO INCIDENTS_SPATIAL (MONGO_ID, title, LOCATION)
VALUES (
  'dummy_mongo_id_1',
  'Test Incident',
  SDO_GEOMETRY(
    2001, -- 2D Point
    4326, -- SRID WGS84
    SDO_POINT_TYPE(-73.935242, 40.730610, NULL), -- Long, Lat (NY Example)
    NULL, 
    NULL
  )
);

COMMIT;

PROMPT "Spatial Table and Index Created Successfully.";
